server.port : 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Millennium_Hardware?createDatabaseIfNotExist=true
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true